### ISSUE TITLE
Random server crash due to NPE

### ISSUE THREAD

**Issue by xenoflot** [Lordmau5/FFS#5]
**FancyFluidStorage Version**:
1.10.2-2.0.3-b11

**MinecraftForge Version**:
2185

**Client or Server?**:
- [ ] Client
- [X ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:
https://gist.github.com/xenoflot/12ce57bac5cb2e96c2cc177e9dafee68

**What happens / happened?**:
Updated our server tonight and was checking out a recipe bug. Looked at something in JEI and the server crashed. Client did no crash. No other players online at the time. At first I thought the events were related, but after the server came back up, I went in and looked at exactly the same recipe with no problem.

I've put the tail of the log in the gist above. Reporting here first since FFS gets mentioned first. If you'd like me to log with another author, I'm happy to do so.

I can see that the xu2 quarry is mentioned in the crash. I only know of one xu2 quarry on the server. It's probably out of render range from my base and the spawn chunks but is probably chunkloaded.

extrautils2 ver 1.10.2-1.2.0

**How can we reproduce it?**:
No idea, sorry. I don't believe it was related to anything I was doing on the server at the time.

**Comment by gigabit101** [comment]
this is fixed in 1.12

**Comment by brisingraerowing** [comment]
Is this in a released version? I am on 2.1.3 (which apparently identifies itself as 2.1.2 in mcmod.info) and still get this exact crash.

MC 1.12.1

EDIT: [Crash Log](https://gist.github.com/BrisingrAerowing/b80583f6986d881f41d846a79184f570)
